const programs = [
  "Accounting and Financial Management",
  "Actuarial Science",
  "Anthropology",
  "Applied Mathematics",
  "Applied Mathematics with Scientific Computing and Scientific Machine Learning",
  "Architectural Engineering",
  "Architecture",
  "Bachelor of Arts",
  "Bachelor of Science",
  "Biochemistry",
  "Biological and Medical Physics",
  "Biology",
  "Biomedical Engineering",
  "Biomedical Sciences",
  "Biostatistics",
  "Business Administration (Laurier) and Computer Science (Waterloo) Double Degree",
  "Business Administration (Laurier) and Mathematics (Waterloo) Double Degree",
  "Chemical Engineering",
  "Chemistry",
  "Civil Engineering",
  "Classical Studies",
  "Climate and Environmental Change",
  "Combinatorics and Optimization",
  "Communication Studies",
  "Computational Mathematics",
  "Computer Engineering",
  "Computer Science",
  "Computing and Financial Management",
  "Data Science",
  "Earth Sciences",
  "Economics",
  "Education (teaching)",
  "Electrical Engineering",
  "English",
  "Environment and Business",
  "Environment, Resources and Sustainability",
  "Environmental Engineering",
  "Environmental Sciences",
  "Fine Arts",
  "French",
  "Gender and Social Justice",
  "Geography and Aviation",
  "Geography and Environmental Management",
  "Geological Engineering",
  "Geospatial Data Analysis (formerly Geomatics)",
  "Global Business and Digital Arts",
  "Health Sciences",
  "History",
  "Honours Arts",
  "Honours Arts and Business",
  "Honours Science",
  "Human Rights and Law (LLB)",
  "Information Technology Management",
  "Kinesiology",
  "Legal Studies",
  "Liberal Studies",
  "Life Sciences",
  "Management Engineering",
  "Materials and Nanosciences",
  "Mathematical Economics",
  "Mathematical Finance",
  "Mathematical Optimization",
  "Mathematical Physics",
  "Mathematical Studies",
  "Mathematics",
  "Mathematics/Business Administration",
  "Mathematics/Chartered Professional Accountancy",
  "Mathematics/Financial Analysis and Risk Management",
  "Mathematics/Teaching",
  "Mechanical Engineering",
  "Mechatronics Engineering",
  "Medical Sciences (Waterloo) and Doctor of Medicine (St. George's University)",
  "Medicinal Chemistry",
  "Medieval Studies",
  "Music",
  "Nanotechnology Engineering",
  "Optometry",
  "Peace and Conflict Studies",
  "Pharmacy",
  "Philosophy",
  "Physical Sciences",
  "Physics",
  "Physics and Astronomy",
  "Planning",
  "Political Science",
  "Psychology – Bachelor of Arts",
  "Psychology – Bachelor of Science",
  "Public Health",
  "Pure Mathematics",
  "Recreation and Leisure Studies",
  "Recreation, Leadership and Health",
  "Religion, Culture, and Spirituality",
  "Science and Aviation",
  "Science and Business",
  "Science and Financial Management",
  "Sexualities, Relationships, and Families",
  "Social Development Studies",
  "Social Development Studies and Bachelor of Social Work Double Degree",
  "Social Work",
  "Sociology",
  "Software Engineering",
  "Sport and Recreation Management",
  "Statistics",
  "Sustainability and Financial Management",
  "Systems Design Engineering",
  "Teaching",
  "Theatre and Performance",
  "Therapeutic Recreation",
];

const engineeringPrograms = [
  "Architectural Engineering",
  "Biomedical Engineering",
  "Chemical Engineering",
  "Civil Engineering",
  "Computer Engineering",
  "Electrical Engineering",
  "Environmental Engineering",
  "Geological Engineering",
  "Management Engineering",
  "Mechanical Engineering",
  "Mechatronics Engineering",
  "Nanotechnology Engineering",
  "Software Engineering",
  "Systems Design Engineering",
];

const engineeringOptions = [
  "Artificial Intelligence",
  "Biomechanics",
  "Computer Engineering",
  "Computing",
  "Entrepreneurship",
  "Environmental Engineering",
  "Life Sciences",
  "Management Science",
  "Mechatronics",
  "Physical Sciences",
  "Quantum Engineering",
  "Software Engineering",
  "Statistics",
];

const minors = [
  "Anthropology",
  "Applied Language Studies",
  "Canadian Politics and Public Policy",
  "Catholic Studies",
  "Classical Studies",
  "Communication Studies",
  "Digital Arts Communication",
  "Economics",
  "Economic Theory",
  "English",
  "Gender and Social Justice",
  "History",
  "Human Rights",
  "Human Sciences",
  "International Studies",
  "Knowledge Integration",
  "Legal Studies",
  "Medieval Studies",
  "Peace and Conflict Studies",
  "Philosophy",
  "Political Science",
  "Politics and Business",
  "Psychology",
  "Religion, Culture, and Spirituality",
  "Sexualities, Relationships, and Families",
  "Social Development Studies",
  "Social Innovation",
  "Sociology",
  "Technical Writing",
  "Entrepreneurship",
  "Event Management",
  "Human Resources Management",
  "Indigenous Entrepreneurship",
  "International Trade",
  "Management Studies",
  "Tourism",
  "Canadian Studies",
  "Cultural Identities",
  "East Asian Studies",
  "French",
  "German",
  "Indigenous Studies",
  "Italian Studies",
  "Jewish Studies",
  "Mennonite Studies",
  "Russian and East European Studies",
  "Studies in Islamic and Arab Cultures",
  "Spanish",
  "Environment, Resources and Sustainability",
  "Geography and Environmental Management",
  "Parks",
  "Urban Studies",
  "Church Music and Worship",
  "Fine Arts Studio",
  "Music",
  "Performance Creation",
  "Visual Culture in a Global Context",
  "Applied Mathematics",
  "Combinatorics and Optimization",
  "Computing",
  "Pure Mathematics",
  "Mathematics",
  "Addictions, Mental Health, and Policy",
  "Astrophysics",
  "Biochemistry",
  "Biology",
  "Biophysics",
  "Chemistry",
  "Cognitive Science",
  "Earth Sciences",
  "Ergonomics and Injury Prevention",
  "Gerontology",
  "Human Nutrition",
  "Medical Physiology",
  "Neuroscience",
  "Physics",
];

const termLabels = [
  "1A",
  "1B",
  "2A",
  "2B",
  "3A",
  "3B",
  "4A",
  "4B",
  "Co-op 1",
  "Co-op 2",
  "Co-op 3",
  "Co-op 4",
  "Co-op 5",
  "Co-op 6",
];

module.exports = {
  programs,
  engineeringPrograms,
  engineeringOptions,
  minors,
  termLabels,
};